#!/bin/sh
basedir=`dirname $0`
echo -n -e "\033k$1\033\\"
case $1 in
ptt*)
    if [ "$2" = "telnet" ] ; then
        $basedir/bbs $1.cc
    else
        ssh bbsu@$1.cc
    fi
    ;;
eod)
    #$basedir/bbs eod.tw
    $basedir/bbs bbs.tcfsh.tc.edu.tw
    ;;
esac

